# Assignment 6

# Text Summarisation

# Text 1

#### Importing libraries to reprocess text data, compute similarity metrics between text elements, and construct and analyze graphs to perform text summarization

In [1]:
from nltk.corpus import stopwords #you can remove stop words for speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx


#### process a paragraph from a text file into individual sentences and then further split them into words

In [2]:
file = open(r"C:\Users\Public\text 1.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))


Ich lese gerne und mag Tiere: Wir haben einen Hund, zwei Katzen und im Garten einen Teich mit Goldfischen
Ich gehe auch gerne in die Schule, mein Lieblingsfach ist Mathematik
Physik und Chemie mag ich nicht so gerne.


#### Prints the sentences

In [3]:
print("Sentences are ", sentences)


Sentences are  [['Ich', 'lese', 'gerne', 'und', 'mag', 'Tiere:', 'Wir', 'haben', 'einen', 'Hund,', 'zwei', 'Katzen', 'und', 'im', 'Garten', 'einen', 'Teich', 'mit', 'Goldfischen'], ['Ich', 'gehe', 'auch', 'gerne', 'in', 'die', 'Schule,', 'mein', 'Lieblingsfach', 'ist', 'Mathematik'], ['Physik', 'und', 'Chemie', 'mag', 'ich', 'nicht', 'so', 'gerne.']]


#### function aims at computing the similarity between two sentences

In [4]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)


#### creates a similarity matrix to store the similarity scores between each pair of sentences.

In [5]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0.         0.12573892 0.29488391]
 [0.12573892 0.         0.10660036]
 [0.29488391 0.10660036 0.        ]]


#### creates a graph from the similarity matrix and then apply PageRank to compute scores for each sentence

In [6]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)


scores {0: 0.3914679821602244, 1: 0.23399789355822842, 2: 0.3745341242815466}


#### ranks the sentences based on their PageRank scores calculated previously

In [7]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.3914679821602244, ['Ich', 'lese', 'gerne', 'und', 'mag', 'Tiere:', 'Wir', 'haben', 'einen', 'Hund,', 'zwei', 'Katzen', 'und', 'im', 'Garten', 'einen', 'Teich', 'mit', 'Goldfischen']), (0.3745341242815466, ['Physik', 'und', 'Chemie', 'mag', 'ich', 'nicht', 'so', 'gerne.']), (0.23399789355822842, ['Ich', 'gehe', 'auch', 'gerne', 'in', 'die', 'Schule,', 'mein', 'Lieblingsfach', 'ist', 'Mathematik'])]


#### takes user input to determine how many sentences should be in the summary

In [8]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=4
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))


How many sentences do you want in the summary? 2


#### prints the summarized text by joining the selected sentences with a period and space in between

In [9]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))


Summarize Text: 
 Ich lese gerne und mag Tiere: Wir haben einen Hund, zwei Katzen und im Garten einen Teich mit Goldfischen. Physik und Chemie mag ich nicht so gerne.


# Text 2

#### process a paragraph from a text file into individual sentences and then further split them into words

In [12]:
file = open(r"C:\Users\Public\text 2.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

La vie en France est très différente de celle au Canada
Ici, il fait toujours chaud
Chaque dimanche, nous allons à la magnifique plage de Biarritz et nous achetons des glaces après avoir nagé dans la mer.Les Français sont très sympathiques et accueillants
Nous parlons français lorsque nous sommes dehors, à l'école ou au marché
Cependant, nous continuons de parler anglais à la maison, car mes parents ne veulent pas que je perde ma langue natale.


#### Prints the sentences

In [13]:
print("Sentences are ", sentences)

Sentences are  [['La', 'vie', 'en', 'France', 'est', 'très', 'différente', 'de', 'celle', 'au', 'Canada'], ['Ici,', 'il', 'fait', 'toujours', 'chaud'], ['Chaque', 'dimanche,', 'nous', 'allons', 'Ã\xa0', 'la', 'magnifique', 'plage', 'de', 'Biarritz', 'et', 'nous', 'achetons', 'des', 'glaces', 'après', 'avoir', 'nagé', 'dans', 'la', 'mer.Les', 'Français', 'sont', 'très', 'sympathiques', 'et', 'accueillants'], ['Nous', 'parlons', 'français', 'lorsque', 'nous', 'sommes', 'dehors,', 'Ã\xa0', "l'école", 'ou', 'au', 'marché'], ['Cependant,', 'nous', 'continuons', 'de', 'parler', 'anglais', 'Ã\xa0', 'la', 'maison,', 'car', 'mes', 'parents', 'ne', 'veulent', 'pas', 'que', 'je', 'perde', 'ma', 'langue', 'natale.']]


#### function aims at computing the similarity between two sentences

In [18]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

#### creates a similarity matrix to store the similarity scores between each pair of sentences.

In [20]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0.         0.         0.20994555 0.0805823  0.13159034]
 [0.         0.         0.         0.         0.        ]
 [0.20994555 0.         0.         0.27914526 0.22792115]
 [0.0805823  0.         0.27914526 0.         0.17496355]
 [0.13159034 0.         0.22792115 0.17496355 0.        ]]


#### creates a graph from the similarity matrix and then apply PageRank to compute scores for each sentence

In [21]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)


scores {0: 0.1910303813442053, 1: 0.03614457832948221, 2: 0.3053273365543461, 3: 0.23333630494180363, 4: 0.2341613988301626}


#### ranks the sentences based on their PageRank scores calculated previously

In [22]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.3053273365543461, ['Chaque', 'dimanche,', 'nous', 'allons', 'Ã\xa0', 'la', 'magnifique', 'plage', 'de', 'Biarritz', 'et', 'nous', 'achetons', 'des', 'glaces', 'après', 'avoir', 'nagé', 'dans', 'la', 'mer.Les', 'Français', 'sont', 'très', 'sympathiques', 'et', 'accueillants']), (0.2341613988301626, ['Cependant,', 'nous', 'continuons', 'de', 'parler', 'anglais', 'Ã\xa0', 'la', 'maison,', 'car', 'mes', 'parents', 'ne', 'veulent', 'pas', 'que', 'je', 'perde', 'ma', 'langue', 'natale.']), (0.23333630494180363, ['Nous', 'parlons', 'français', 'lorsque', 'nous', 'sommes', 'dehors,', 'Ã\xa0', "l'école", 'ou', 'au', 'marché']), (0.1910303813442053, ['La', 'vie', 'en', 'France', 'est', 'très', 'différente', 'de', 'celle', 'au', 'Canada']), (0.03614457832948221, ['Ici,', 'il', 'fait', 'toujours', 'chaud'])]


#### takes user input to determine how many sentences should be in the summary

In [23]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=5
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))


How many sentences do you want in the summary? 4


#### prints the summarized text by joining the selected sentences with a period and space in between

In [24]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))


Summarize Text: 
 Chaque dimanche, nous allons à la magnifique plage de Biarritz et nous achetons des glaces après avoir nagé dans la mer.Les Français sont très sympathiques et accueillants. Cependant, nous continuons de parler anglais à la maison, car mes parents ne veulent pas que je perde ma langue natale.. Nous parlons français lorsque nous sommes dehors, à l'école ou au marché. La vie en France est très différente de celle au Canada


# Text 3

#### process a paragraph from a text file into individual sentences and then further split them into words

In [25]:
file = open(r"C:\Users\Public\text 3.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Si eres deportista y te gusta el agua puedes nadar, si te gusta la nieve puedes esquiar
Si no dispones de mucho tiempo puedes correr o ir en bicicleta.Hay quien prefiere quedarse en casa a ver la televisión, jugar videojuegos o navegar en Internet
Otras actividades para hacer dentro de casa cuando llueve o hace mucho frío son escuchar tu música favorita, leer un buen libro o aprender a tocar un instrumento
Puedes aprovechar tu tiempo libre para estudiar.Si el tiempo es bueno, tal vez quieras ir de compras, salir con amigos a divertirse o pasar tiempo con la familia en algún lugar divertido para todos, como un parque de diversiones, el teatro o el cine
Aprovechar el tiempo libre es importante para tener una vida feliz.


#### Prints the sentences

In [26]:
print("Sentences are ", sentences)

Sentences are  [['Si', 'eres', 'deportista', 'y', 'te', 'gusta', 'el', 'agua', 'puedes', 'nadar,', 'si', 'te', 'gusta', 'la', 'nieve', 'puedes', 'esquiar'], ['Si', 'no', 'dispones', 'de', 'mucho', 'tiempo', 'puedes', 'correr', 'o', 'ir', 'en', 'bicicleta.Hay', 'quien', 'prefiere', 'quedarse', 'en', 'casa', 'a', 'ver', 'la', 'televisión,', 'jugar', 'videojuegos', 'o', 'navegar', 'en', 'Internet'], ['Otras', 'actividades', 'para', 'hacer', 'dentro', 'de', 'casa', 'cuando', 'llueve', 'o', 'hace', 'mucho', 'frÃ\xado', 'son', 'escuchar', 'tu', 'música', 'favorita,', 'leer', 'un', 'buen', 'libro', 'o', 'aprender', 'a', 'tocar', 'un', 'instrumento'], ['Puedes', 'aprovechar', 'tu', 'tiempo', 'libre', 'para', 'estudiar.Si', 'el', 'tiempo', 'es', 'bueno,', 'tal', 'vez', 'quieras', 'ir', 'de', 'compras,', 'salir', 'con', 'amigos', 'a', 'divertirse', 'o', 'pasar', 'tiempo', 'con', 'la', 'familia', 'en', 'algún', 'lugar', 'divertido', 'para', 'todos,', 'como', 'un', 'parque', 'de', 'diversiones,

#### function aims at computing the similarity between two sentences

In [27]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

#### creates a similarity matrix to store the similarity scores between each pair of sentences.

In [28]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0.         0.16903085 0.         0.15       0.06030227]
 [0.16903085 0.         0.23904572 0.3380617  0.05096472]
 [0.         0.23904572 0.         0.26516504 0.05330018]
 [0.15       0.3380617  0.26516504 0.         0.4145781 ]
 [0.06030227 0.05096472 0.05330018 0.4145781  0.        ]]


#### creates a graph from the similarity matrix and then apply PageRank to compute scores for each sentence

In [29]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.12082481777487625, 1: 0.2267064935259036, 2: 0.1629122690466176, 3: 0.3208522527187359, 4: 0.16870416693386664}


#### ranks the sentences based on their PageRank scores calculated previously

In [30]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.3208522527187359, ['Puedes', 'aprovechar', 'tu', 'tiempo', 'libre', 'para', 'estudiar.Si', 'el', 'tiempo', 'es', 'bueno,', 'tal', 'vez', 'quieras', 'ir', 'de', 'compras,', 'salir', 'con', 'amigos', 'a', 'divertirse', 'o', 'pasar', 'tiempo', 'con', 'la', 'familia', 'en', 'algún', 'lugar', 'divertido', 'para', 'todos,', 'como', 'un', 'parque', 'de', 'diversiones,', 'el', 'teatro', 'o', 'el', 'cine']), (0.2267064935259036, ['Si', 'no', 'dispones', 'de', 'mucho', 'tiempo', 'puedes', 'correr', 'o', 'ir', 'en', 'bicicleta.Hay', 'quien', 'prefiere', 'quedarse', 'en', 'casa', 'a', 'ver', 'la', 'televisión,', 'jugar', 'videojuegos', 'o', 'navegar', 'en', 'Internet']), (0.16870416693386664, ['Aprovechar', 'el', 'tiempo', 'libre', 'es', 'importante', 'para', 'tener', 'una', 'vida', 'feliz.']), (0.1629122690466176, ['Otras', 'actividades', 'para', 'hacer', 'dentro', 'de', 'casa', 'cuando', 'llueve', 'o', 'hace', 'mucho', 'frÃ\xado', 'son', 'escucha

#### takes user input to determine how many sentences should be in the summary

In [31]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=3
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


#### prints the summarized text by joining the selected sentences with a period and space in between

In [32]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))


Summarize Text: 
 Puedes aprovechar tu tiempo libre para estudiar.Si el tiempo es bueno, tal vez quieras ir de compras, salir con amigos a divertirse o pasar tiempo con la familia en algún lugar divertido para todos, como un parque de diversiones, el teatro o el cine. Si no dispones de mucho tiempo puedes correr o ir en bicicleta.Hay quien prefiere quedarse en casa a ver la televisión, jugar videojuegos o navegar en Internet. Aprovechar el tiempo libre es importante para tener una vida feliz.
